### PR TITLE
Fix option lazyLoad: false

### PR DESCRIPTION
**Pull request by dcyriller**
#### Description
[//]: # "Please include a summary of the change. Imagine you're trying to explain the changes to a reviewer."
After https://github.com/qonto/ember-phone-input/pull/151, option `lazyLoad: false` is broken.

#### Changes
[//]: # "Add if relevant, remove if not"
* Remove the custom script injection for intlTelInput
* Instead make sure the library is loaded (or load it) and then initialize the component

### CODE REVIEW

**Comment by Turbo87** [comment]
so that essentially removes the `lazyLoad` option?! 🤔

**Comment by dcyriller** [comment]
Not really, the lazyLoading is done here now: https://github.com/qonto/ember-phone-input/blob/v3.1.0/addon/services/phone-input.js#L14

**Comment by dcyriller** [comment]
You mean: with that PR, the script would _always_ be loaded? The answer to that question is: yes.

The lazyLoad option allow users to load the script in the init hook of the phoneInput service (meaning at app boot). Note that previously it was loaded from `index.html` file. Which is a small change.

If they specify `lazyLoad: true`. The script won't be loaded at app boot. Instead they will have to load it manually. If they don't, a fallback will load the script before doing the component setup.

**Comment by dcyriller** [comment]
@Turbo87 do you have time to review it? If not, I will merge it to release the fix.

**Pull request merged**
