### PR TITLE
Fix maximum callstack bug when using tracked properties in consuming app

### PR DESCRIPTION
**Pull request by mansona**
#### Description
[//]: # "Please include a summary of the change. Imagine you're trying to explain the changes to a reviewer."

This PR adds a reproduction of the issue that was caused in a simple acceptance test. You can see in the [simplest recreation using a tracked property here](https://github.com/qonto/ember-phone-input/pull/354/files#diff-7b29266f44d218cbcf748fc12818c8720758b42a655d6f381e7be47bf84d140eR1) with it's corresponding template and as you can see with the failing test on the first commit of this PR this will fail with a ["Maximum callstack exceeded" error](https://github.com/qonto/ember-phone-input/pull/354/checks?check_run_id=3288831492#step:5:26).

The second commit fixes this by only calling `this.update()` on the component when the value has actually changed 👍

### CODE REVIEW

**Comment by dbendaou** [comment]
Shall we release a new patch for this one?

**Comment by mansona** [comment]
@dbendaou so the previous 2 PRs have been breaking so we would need to release a major anyway. We could backport just this change if we felt like it. What do you think? 

I'd be inclined just to do a major once this is merged for simplicity 🤷

**Comment by dbendaou** [comment]
@mansona sounds good to me 👍

**Comment by m-jovan** [comment]
Closing this due to inactivity

**Pull request closed without merging**
