### PR TITLE
Remove ember-decorators dependency

### PR DESCRIPTION
**Pull request by kiwiupover**
Remove the decorators from the `phone-input` component
updated super
adding input type

http://phone-input.surge.sh -> use this branch
http://phone-input-broken.surge.sh -> uses `2.0.5`

The above app can be found here 
https://github.com/kiwiupover/phone-input
https://github.com/kiwiupover/phone-input/tree/broken

### CODE REVIEW

**Comment by kiwiupover** [comment]
@jacojoubert FYI

**Comment by dcyriller** [comment]
@kiwiupover thank you for the reproduction. I'll be able to check it out on Monday, I don't have IE 11 at home.

I'd be interested to know the root cause of this transpilation issue. Do you have an idea?

**Comment by jacojoubert** [comment]
The issue was fixed by adding https://github.com/pzuraq/ember-cli-babel-polyfills which properly compiles the decorators to something IE11 can understand.

**Comment by dcyriller** [comment]
Good to know @jacojoubert.

I want to procede with the decorator removal. To do so, I've added two commits.

@kiwiupover I've rebased the PR, thank you for your work.

**Pull request merged**
