### PR TITLE
Feature add attribute biding for disabled

### PR DESCRIPTION
**Pull request by vsergiu93**
I needed to be able to disabled the input so I just made a PR, it's just adding `disabled` to attribute bindings and added a test case for it.

### CODE REVIEW

**Comment by dbendaou** [comment]
Hello ! 
Thanks for your contribution ! Could you please add some doc on the dummy app about this new attribute ? :)

**Comment by vsergiu93** [comment]
Hello !

Yes I can, I will do it later today.

Thanks for the quick response on the PR.

**Comment by vsergiu93** [comment]
@dbendaou Is it ok now? :)

**Comment by dbendaou** [comment]
Doing so QA right now will get back to you ASAP :)

**Comment by dbendaou** [comment]
@vsergiu93 I've merged it, thanks again !

**Comment by vsergiu93** [comment]
@dbendaou thank you also for your time :)

**Comment by dcyriller** [comment]
Released in a v3.1.0

**Pull request merged**
