### PR TITLE
Add binding for autocomplete

### PR DESCRIPTION
**Pull request by lan0**
#### Description

Adds attributeBinding for autocomplete, to use `autocomplete="tel"`

### CODE REVIEW

**Comment by dbendaou** [comment]
Thanks for this ! 
Just have the new created test that his failing otherwise LGTM ! 


Here's the failing test below:
```
not ok 9 Chrome 62.0 - [91 ms] - Integration | Component | phone-input: can set autocomplete
    ---
        actual: >
            off
        expected: >
            tel
        stack: >
                at _callee10$ (http://localhost:4203/assets/tests.js:403:24)
                at tryCatch (http://localhost:4203/assets/vendor.js:413:40)
                at Generator.invoke [as _invoke] (http://localhost:4203/assets/vendor.js:687:22)
                at Generator.prototype.(anonymous function) [as next] (http://localhost:4203/assets/vendor.js:446:21)
                at asyncGeneratorStep (http://localhost:4203/assets/tests.js:61:105)
                at _next (http://localhost:4203/assets/tests.js:63:196)
        negative: >
            false
        browser log: |
    ...
```


Once it's fixed I'll be ready to be merged 😊

**Comment by lan0** [comment]
I've added `autocomplete` and documentation to the init() method and fixed the test by bumping intl-tel-input.

See https://github.com/jackocnr/intl-tel-input/issues/668#issuecomment-612094976

**Comment by dbendaou** [comment]
Just a minor change, I've merged the update of https://github.com/qonto/ember-phone-input/pull/229 so you can rebase and drop the commit that bump the intl-tel-input version :) 

(I would rather keep updates and features in separate MRs)

**Comment by lan0** [comment]
Oh I see, thanks for the merge.

**Comment by dbendaou** [comment]
I will push a new release so this change will be available

**Comment by dbendaou** [comment]
Released in 5.1.0

**Pull request merged**
